theme: jekyll-theme-minimal
title: Wikispeedia World Cup
description: A vibrant competition between different wikispeedia hubs.
show_downloads: True
navigation:
   - title: Home
     url: /
   - title: The Competitors
     url: competitors
   - title: Betting Floor
     url: betting-floor
   - title: Structure of the Tournament
     url: tournament-structure
   - title: Start of the World Cup of Hubs
     url: start-tournament
   - title: The Deadly Knockouts
     url: knockouts
   - title: The Grand Final
     url: final
   - title: Analysis and Insights
     url: analysis
